export interface ProjectItem {
  id: string
  name: string
  category: string
  description?: string
  poster: string
  videoMp4?: string
  videoWebm?: string
  urlTag: string
  aspectRatio?: string
}

// 5 Curated Showcase Projects for Hero
export const heroShowcaseProjects: ProjectItem[] = [
  {
    id: "oxford-cove",
    name: "OXFORD COVE",
    category: "Dubai Luxury Real Estate",
    description: "Plataforma digital de alto padrão para mercado imobiliário internacional em Dubai.",
    poster: "/projects/video-optimized/oxford-cove.webp",
    videoMp4: "/projects/video-optimized/oxford-cove.mp4",
    videoWebm: "/projects/video-optimized/oxford-cove.webm",
    urlTag: "oxfordcove.ae",
  },
  {
    id: "glemo",
    name: "GLEMO",
    category: "Hub Imobiliário B2B",
    description: "Plataforma e landing page B2B conectando imobiliárias e corretores a lançamentos exclusivos.",
    poster: "/projects/video-optimized/glemo.webp",
    videoMp4: "/projects/video-optimized/glemo.mp4",
    videoWebm: "/projects/video-optimized/glemo.webm",
    urlTag: "glemo.com.br",
  },
  {
    id: "beruf",
    name: "BERUF BRASIL",
    category: "Soluções Industriais",
    description: "Site corporativo e catálogo técnico para indústria nacional de alta precisão.",
    poster: "/projects/video-optimized/beruf.webp",
    videoMp4: "/projects/video-optimized/beruf.mp4",
    videoWebm: "/projects/video-optimized/beruf.webm",
    urlTag: "beruf.com.br",
  },
  {
    id: "linhas-e-formas",
    name: "LINHAS E FORMAS",
    category: "Design de Interiores & Arquitetura",
    description: "Site minimalista e galeria visual para escritório de design de interiores.",
    poster: "/projects/video-optimized/linhas-e-formas.webp",
    videoMp4: "/projects/video-optimized/linhas-e-formas.mp4",
    videoWebm: "/projects/video-optimized/linhas-e-formas.webm",
    urlTag: "linhaseformas.com.br",
  },
  {
    id: "hollywood-wg",
    name: "HOLLYWOOD WG",
    category: "Barbearia & Estética Premium",
    description: "Plataforma digital e agendamento de serviços para barbearia de alto padrão.",
    poster: "/projects/video-optimized/hollywood-wg.webp",
    videoMp4: "/projects/video-optimized/hollywood-wg.mp4",
    videoWebm: "/projects/video-optimized/hollywood-wg.webm",
    urlTag: "hollywoodwg.com.br",
  },
]

// All Real Projects for the Comprehensive Portfolio Gallery
export const allProjects: ProjectItem[] = [
  {
    id: "oxford-cove",
    name: "OXFORD COVE",
    category: "Dubai Luxury Real Estate",
    description: "Plataforma digital para mercado imobiliário internacional em Dubai.",
    poster: "/projects/video-optimized/oxford-cove.webp",
    videoMp4: "/projects/video-optimized/oxford-cove.mp4",
    videoWebm: "/projects/video-optimized/oxford-cove.webm",
    urlTag: "oxfordcove.ae",
  },
  {
    id: "glemo",
    name: "GLEMO",
    category: "Hub Imobiliário B2B",
    description: "Landing page e ecossistema digital para intermediações corporativas.",
    poster: "/projects/video-optimized/glemo.webp",
    videoMp4: "/projects/video-optimized/glemo.mp4",
    videoWebm: "/projects/video-optimized/glemo.webm",
    urlTag: "glemo.com.br",
  },
  {
    id: "beruf",
    name: "BERUF BRASIL",
    category: "Soluções Industriais",
    description: "Estrutura institucional para multinacional do setor fabril e engenharia.",
    poster: "/projects/video-optimized/beruf.webp",
    videoMp4: "/projects/video-optimized/beruf.mp4",
    videoWebm: "/projects/video-optimized/beruf.webm",
    urlTag: "beruf.com.br",
  },
  {
    id: "mitocafes",
    name: "MITO CAFÉS",
    category: "Cafés Especiais",
    description: "Identidade digital e canal comercial para marca de cafés premiados.",
    poster: "/projects/video-optimized/mitocafes.webp",
    videoMp4: "/projects/video-optimized/mitocafes.mp4",
    videoWebm: "/projects/video-optimized/mitocafes.webm",
    urlTag: "mitocafes.com.br",
  },
  {
    id: "hollywood-wg",
    name: "HOLLYWOOD WG",
    category: "Barbearia & Estética Premium",
    description: "Plataforma digital e agendamento de serviços para barbearia de alto padrão.",
    poster: "/projects/video-optimized/hollywood-wg.webp",
    videoMp4: "/projects/video-optimized/hollywood-wg.mp4",
    videoWebm: "/projects/video-optimized/hollywood-wg.webm",
    urlTag: "hollywoodwg.com.br",
  },
  {
    id: "portas-abertas",
    name: "DE PORTAS ABERTAS",
    category: "Editorial & Conteúdo",
    description: "Blog e portal de artigos imobiliários com foco em SEO e leitura fluida.",
    poster: "/projects/video-optimized/portas-abertas.webp",
    videoMp4: "/projects/video-optimized/portas-abertas.mp4",
    videoWebm: "/projects/video-optimized/portas-abertas.webm",
    urlTag: "deportasabertas.com.br",
  },
  {
    id: "linhas-e-formas",
    name: "LINHAS E FORMAS",
    category: "Design de Interiores",
    description: "Site minimalista e galeria visual para escritório de design de interiores.",
    poster: "/projects/video-optimized/linhas-e-formas.webp",
    videoMp4: "/projects/video-optimized/linhas-e-formas.mp4",
    videoWebm: "/projects/video-optimized/linhas-e-formas.webm",
    urlTag: "linhaseformas.com.br",
  },
  {
    id: "menin",
    name: "MENIN ENGENHARIA",
    category: "Lançamento Imobiliário",
    description: "Landing page de alta conversão para empreendimento residencial.",
    poster: "/projects/video-optimized/menin.webp",
    videoMp4: "/projects/video-optimized/menin.mp4",
    videoWebm: "/projects/video-optimized/menin.webm",
    urlTag: "menin.com.br",
  },
  {
    id: "mrv-co",
    name: "MRV&CO",
    category: "Construção Civil",
    description: "Experiência digital para apresentação corporativa e captação de leads.",
    poster: "/projects/video-optimized/mrv-co.webp",
    videoMp4: "/projects/video-optimized/mrv-co.mp4",
    videoWebm: "/projects/video-optimized/mrv-co.webm",
    urlTag: "mrv.com.br",
  },
  {
    id: "multimed",
    name: "MULTIMED",
    category: "Saúde & Tecnologia",
    description: "Portal de serviços e agendamento para rede de clínicas médicas.",
    poster: "/projects/video-optimized/multimed.webp",
    videoMp4: "/projects/video-optimized/multimed.mp4",
    videoWebm: "/projects/video-optimized/multimed.webm",
    urlTag: "multimed.com.br",
  },
  {
    id: "penseopen",
    name: "PENSE OPEN",
    category: "Inovação & Gestão",
    description: "Landing page para consultoria estratégica e transformação digital.",
    poster: "/projects/video-optimized/penseopen.webp",
    videoMp4: "/projects/video-optimized/penseopen.mp4",
    videoWebm: "/projects/video-optimized/penseopen.webm",
    urlTag: "penseopen.com.br",
  },
  {
    id: "kast",
    name: "KAST",
    category: "Soluções Digitais",
    description: "Plataforma web para gestão de processos e automação corporativa.",
    poster: "/projects/video-optimized/kast.webp",
    videoMp4: "/projects/video-optimized/kast.mp4",
    videoWebm: "/projects/video-optimized/kast.webm",
    urlTag: "kast.com.br",
  },
  {
    id: "pride",
    name: "PRIDE CONSTRUTORA",
    category: "Incorporação Imobiliária",
    description: "Página de apresentação e vendas para linha de empreendimentos urbanos.",
    poster: "/projects/video-optimized/pride.webp",
    videoMp4: "/projects/video-optimized/pride.mp4",
    videoWebm: "/projects/video-optimized/pride.webm",
    urlTag: "construtorapride.com.br",
  },
  {
    id: "rogga",
    name: "ROGGA EMPREENDIMENTOS",
    category: "Real Estate & Lazer",
    description: "Site com catálogo interativo de apartamentos no litoral.",
    poster: "/projects/video-optimized/rogga.webp",
    videoMp4: "/projects/video-optimized/rogga.mp4",
    videoWebm: "/projects/video-optimized/rogga.webm",
    urlTag: "rogga.com.br",
  },
  {
    id: "sa-cavalcante",
    name: "SÁ CAVALCANTE",
    category: "Shopping Centers & Negócios",
    description: "Portal institucional e área de locação para grupo empresarial.",
    poster: "/projects/video-optimized/sa-cavalcante.webp",
    videoMp4: "/projects/video-optimized/sa-cavalcante.mp4",
    videoWebm: "/projects/video-optimized/sa-cavalcante.webm",
    urlTag: "sacavalcante.com.br",
  },
  {
    id: "widestep",
    name: "WIDESTEP",
    category: "Software & Tecnologia",
    description: "Landing page técnica para produto digital SaaS de alta performance.",
    poster: "/projects/video-optimized/widestep.webp",
    videoMp4: "/projects/video-optimized/widestep.mp4",

    urlTag: "widestep.com",
  },
  {
    id: "brz",
    name: "BRZ EMPREENDIMENTOS",
    category: "Engenharia & Habitação",
    description: "Apresentação comercial e simulação de imóveis para construtora.",
    poster: "/projects/video-optimized/brz.webp",
    videoMp4: "/projects/video-optimized/brz.mp4",
    videoWebm: "/projects/video-optimized/brz.webm",
    urlTag: "brzempreendimentos.com.br",
  },
  {
    id: "academia-da-fala",
    name: "ACADEMIA DA FALA",
    category: "Educação & Oratória",
    description: "Plataforma de cursos e desenvolvimento em comunicação e oratória profissional.",
    poster: "/projects/video-optimized/academia-da-fala.webp",
    videoMp4: "/projects/video-optimized/academia-da-fala.mp4",
    urlTag: "academiadafala.com.br",
  },
  {
    id: "barbaros-tattoo",
    name: "BÁRBAROS TATTOO CLUB",
    category: "Tatuagem & Estética",
    description: "Site conceitual e agendamento para estúdio de tatuagem e arte corporal.",
    poster: "/projects/video-optimized/barbaros-tattoo.webp",
    videoMp4: "/projects/video-optimized/barbaros-tattoo.mp4",
    urlTag: "barbarostattooclub.com.br",
  },
  {
    id: "buzzvel",
    name: "BUZZVEL",
    category: "Software & Agência Digital",
    description: "Apresentação corporativa e portfólio digital para software house.",
    poster: "/projects/video-optimized/buzzvel.webp",
    urlTag: "buzzvel.com",
  },
  {
    id: "andyglobalshop",
    name: "ANDY GLOBAL SHOP",
    category: "E-commerce & Importados",
    description: "Plataforma de comércio eletrônico internacional com catálogo completo de produtos.",
    poster: "/projects/video-optimized/andyglobalshop.webp",
    videoMp4: "/projects/video-optimized/andyglobalshop.mp4",
    urlTag: "andyglobalshop.com",
  },
  {
    id: "credit-black",
    name: "CREDIT BLACK",
    category: "Finanças & Cartões Black",
    description: "Plataforma de consultoria e soluções financeiras para cartões de alta renda e investimentos.",
    poster: "/projects/video-optimized/credit-black.webp",
    videoMp4: "/projects/video-optimized/credit-black.mp4",
    urlTag: "creditblack.com.br",
  },
  {
    id: "bmpi",
    name: "BMPI",
    category: "Investimentos & Gestão de Ativos",
    description: "Portal institucional e portfólio estratégico para gestora de investimentos e ativos imobiliários.",
    poster: "/projects/video-optimized/bmpi.webp",
    videoMp4: "/projects/video-optimized/bmpi.mp4",
    videoWebm: "/projects/video-optimized/bmpi.webm",
    urlTag: "bmpi.com.br",
  },
  {
    id: "sensia",
    name: "SENSIA",
    category: "Mercado Imobiliário",
    description: "Plataforma e projeto digital focados em experiência premium no segmento imobiliário.",
    poster: "/projects/video-optimized/sensia.webp",
    videoMp4: "/projects/video-optimized/sensia.mp4",
    urlTag: "sensiaincorporadora.com.br",
  },
]
